on:
    push:
      branches:
        - main

jobs:
  Build and Publish:
    runs-on: ubuntu-20.04
    strategy:
        matrix:
          target_images: [first, second, third]
        fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image(s)
        run: |
          docker build -f docker-images/${{ matrix.target_images }}/Dockerfile -t ${{ matrix.target_images }}:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ matrix.target_images }}:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'



      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'