Name: Publish Docker Images

on:
    push:
    branches: [ "main" ]

jobs:
  name: Build
  runs-on: ubuntu-20.04
  strategy:
      matrix:
        target_images: [first, second, third]
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker Image(s)
      run: |
        docker build -f docker-images/${{ target_images }} -t ${{ target_images }}:${{ github.sha }} .

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'docker-images/${{ target_images }}:${{ github.sha }}'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'